name: Cron Nowcat Bot

on:
  schedule:
    - cron: '0,20,40 * * * *'
  push:
    branches:
      - master

jobs:
  build:
    name: Run bot
    runs-on: ubuntu-latest
    steps:
      - uses: robinraju/release-downloader@v1.4
        with:
          latest: true
          fileName: "*_linux_amd64.tar.gz"
      - name: unarchive
        run: tar -zxvf /home/runner/work/nowcast-bot/nowcast-bot/*.tar.gz ././nowcast-bot
      - name: run
        run: ./nowcast-bot
        env:
          SLACK_WEBHOOK:  ${{secrets.SLACK_WEBHOOK}}
          GYAZO_TOKEN: ${{secrets.GYAZO_TOKEN}}
          POS_X: ${{secrets.POS_X}}
          POS_Y: ${{secrets.POS_Y}}
          MAP_ID: ${{secrets.MAP_ID}}
